### PR TITLE
Pianoroll Single-Select

### PR DESCRIPTION
**Pull request by timgrant**
I've added a single-select to Pattern.getNotesAtTick. If the flag is set, instead of returning an array of all notes that fall across a given tick, it returns the shortest note. This is useful for selecting one of two or more overlapping notes.

### CODE REVIEW

**Comment by timgrant** [comment]
I just realized I should add a mode that also returns any selected notes for ctrl-clicking.

**Comment by timgrant** [comment]
Okay, I think single select is working pretty well.

**Comment by timgrant** [comment]
I fixed an issue where notes would be inadvertently copied when trying to ctrl-click them. The minimum delta for copying is 15 ticks or the current quantization value, whichever is greater.

**Comment by timsama** [comment]
I like it, except that if I select a note in one click, and then try to move it with a subsequent click+drag, it moves the note beneath it.

**Comment by timgrant** [comment]
Ah, yeah. Not quite sure how to handle it. I think maybe getSelectedNotes is being called too soon in the front end. Perhaps there is some better way to identify a move and just move the selected note(s).

**Comment by timgrant** [comment]
It only seems to do that if you click and drag on the non-selected note. I agree that the behavior could be refined, but I think it's a huge improvement over the current implementation.

**Comment by timsama** [comment]
Try a small note that's completely enveloped in a larger note. The first click on the small note selects it, the second click selects the larger note.

**Comment by timsama** [comment]
Don't get me wrong, it's definitely a big improvement over the current implementation. I usually click once to select, then drag, so it's especially irritating for me.

**Comment by timsama** [comment]
I'll merge it, but if you have time, see if you can figure out a way to handle that one case.

**Comment by timgrant** [comment]
That's a somewhat pathological case, and without some sort of note ordering (in terms of the 'z' axis), I don't think there's a good way way around it. But I'll try to figure something out.

**Comment by timsama** [comment]
There's more important stuff to work on, to be sure, so don't sweat it too much. I'll see if I can come up with something as well.

**Pull request merged**
