### PR TITLE
Keyboard expansion, improved countdown, loop control using music clock

### PR DESCRIPTION
**Pull request by timsama**
Keyboard now has 128 keys, and countdown timer displays days instead of hour:min:sec when hours > 24. Weird behavior on notes with pitch 127 and 128; I'm guessing it's a rhombus bug of some kind.

### CODE REVIEW

**Comment by timgrant** [comment]
I can't check this out at the moment, but for the record the notes should be in the range 0-127. What's the weird behavior?

**Comment by timsama** [comment]
Duly noted. It still occurs on pitch 127, though. It starts endlessly playing the same note (and you can't stop it) and gives the error message "Uncaught InvalidAccessError: Failed to execute 'setValueAtTime' on 'AudioParam': Target value must be a finite number: NaN". You'll probably have to try a few times to get it to happen.

**Comment by timgrant** [comment]
I'll check this out right now. Sounds like a Tone thing.

**Comment by timgrant** [comment]
Ah, this is a Rhombus issue. The pitch frequency table is only being computed for notes 0-126. I'll make the change.

**Comment by timgrant** [comment]
I notice that the lowest note on the keyboard (which appears as a C on the keyboard) has a pitch of 1, when it should be 0.

I've fixed the Rhombus issue, and added a function to re-initialize the song. I can update Rhombus after we merge this request.

**Comment by timsama** [comment]
Ok. I have some unrelated changes to put a different pull request, and I'll decrement the pitch there.

**Comment by timsama** [comment]
Decided to just include the loop changes in this one so the pitch fix is all in one place

**Comment by timsama** [comment]
Oh, and weirdly (I checked, I'm giving it the correct value) when I try to add a rhombus note with pitch 0, it creates a note with pitch 60. Every other value works fine, but for some reason, 0 yields a 60

**Comment by timgrant** [comment]
Ah, that's a Rhombus/JavaScript thing... (checking for undefined in a dumb way). Ignore it for now. I've made a few tweaks to Rhombus, so I'll fix that before I update the version on SoundSplosion.

**Comment by timsama** [comment]
Well then we should be good to merge, I think.

**Comment by timgrant** [comment]
Loop controls look awesome. But for some reason, it looks like you can't change the loop start measure. I'll merge this for now and we can worry about it in the AM.

**Pull request merged**
