### PR TITLE
Pattern Editor End Marker

### PR DESCRIPTION
**Pull request by timgrant**
I have (crudely) prevented the end marker from being displayed in the pattern editor. Before, opening the editor set the length of the song to be the length of the pattern being edited, which is undesirable for a number of reasons. 

So I have stopped the overlay from being drawn and fixed the size of the editor window to 16 bars.

### CODE REVIEW

**Comment by timsama** [comment]
image
This happens when you reopen a pattern you've edited.

**Comment by timsama** [comment]
I would recommend instead just fixing the endmarker at 16.

**Comment by timgrant** [comment]
Do you mean for the whole song? Or just for the pattern editor?

**Comment by timsama** [comment]
Just for the pattern editor. If you revert that last commit, I'll fix it at 16 and make it so users can't move it.

**Comment by timgrant** [comment]
The important part is not changing the length of the song when the pattern editor is opened, which is really what I was trying to do.

**Comment by timsama** [comment]
I have the needed changes done on my branch (not yet committed).

**Comment by timgrant** [comment]
Okay, lemme revert this real quick.

**Comment by timgrant** [comment]
Should be good, assuming the sample changes from the last pull request are okay.

**Pull request merged**
