### PR TITLE
Note Recording

### PR DESCRIPTION
**Pull request by timgrant**
To record notes, arm record by pressing the record button on the transport bar and press play. Any notes played on the pianoroll keyboard or on a connected MIDI keyboard will be stored in a temporary buffer. When playback is stopped or the record button is pressed again, the notes will be copied from the buffer into the current pattern.

Record can only be armed from a pattern editor tab, and switching to any other tab will disarm record and clear the record buffer (scorched earth policy). Weird stuff will happen if you manually seek around while recording, so don't do it.

### CODE REVIEW

**Comment by jamie-yu0** [comment]
For some reason, recorded nodes are not showing up in the track view. Maybe I'm doing it wrong. I'll bring that up on the next meeting.

**Comment by timgrant** [comment]
To record notes into a pattern, you must have its editor tab open and in the foreground. If you arm record (by pressing the record button, which should turn red) and press play, any notes you play should be recorded into the buffer. If you stop playback and disarm recording, the notes should be copied from the buffer into the pattern. Is that not working?

**Comment by jamie-yu0** [comment]
I followed your instruction, but I still don't see the notes copied from the buffer. I put a debug point on Rhombus, and it seems like addToBuffer is never called.
screen shot 2015-04-06 at 9 43 43 am

**Comment by timgrant** [comment]
This might be a Mac-specific issue, because it seems to be working fine in Windows and Linux. We're having a meeting at 10:30. If you want, you can come and show me what's happening.

**Comment by sphippen** [comment]
Looks like we worked this out.

**Comment by sphippen** [comment]
By which I mean we tested it in meeting and there was a misunderstanding, it actually works.

**Pull request merged**
