### PR TITLE
Mostly implemented

### PR DESCRIPTION
**Pull request by timsama**
Different patterns can be edited and the changes saved, event bugs have been fixed, and new patterns can be created by pressing the add button. Still need to add ability to remove a pattern, interface with the backend for placing patterns, and style the patterns list a bit.

### CODE REVIEW

**Comment by timgrant** [comment]
When I open the pattern editor, the entire area where the pattern editor should be is blank. Pressing escape doesn't bring back the track view.

missing_editor

**Comment by timsama** [comment]
Ok, I'm on it.

**Comment by timsama** [comment]
Ok, you can pull the trigger whenever, I'm just adding some cosmetic changes right now.

**Comment by timgrant** [comment]
Bombs away.

**Pull request merged**
