### PR TITLE
Effects Graph Overhaul

### PR DESCRIPTION
**Pull request by timsama**
Effects graph now uses the new interface, and has added a context menu on right click to add effects. Drag a node's input to another node's output, or output to input to make a new connection.

### CODE REVIEW

**Comment by timsama** [comment]
However, graphX and graphY are still not saved, so you have to reposition everything every time.

**Comment by sphippen** [comment]
Ah, having to reposition the graph nodes is my fault, an oversight (i.e. bug) in the implementation. https://github.com/soundsplosion/Rhombus/pull/87 fixes that.

**Comment by sphippen** [comment]
... but I just realized that this uses the code from the sp-graph branch, which is separate from that pull request. I'll just open a pull request in this repository in the fixed code after this pull request gets merged.

**Comment by sphippen** [comment]
I ran into problems adding patterns; a little investigation showed this is because the version of Rhombus in here requires AVL.js file on the same page (adding AVL.js fixed it). @timgrant added this in an earlier pull request, but it looks like you don't have that change. I'll make a commit adding it on this pull request, and we'll be good to go.

**Pull request merged**
