### PR TITLE
Rollback to Sqlite, add browser tab icon, use track id to ensure uniqueness

### PR DESCRIPTION
**Pull request by jamie-yu0**

### CODE REVIEW

**Comment by timgrant** [comment]
In the track player, the Rhombus object is undefined.

**Comment by jamie-yu0** [comment]
Is Rhombus object undefined for tracks that you previously created? It should be. I've changed ids of Rhombus from rhombus_trackTitle to rhombus_trackId to avoid duplicate rhombus for tracks with same title. Files will be saved as public/uploads/track_id.

**Comment by timgrant** [comment]
Rhombus is undefined, even if I am saving a brand new track to a fresh database. I looked in public/uploads, and it doesn't look like any files are being saved there. If you come to the meeting tomorrow I can show you what's happening. 

Here's a screenshot from Chrome:

undefined_rhombus

**Comment by jamie-yu0** [comment]
The bug where rhombus is not defined is fixed.

**Pull request merged**
